### ISSUE TITLE
"Exception saving profile preferences"

### ISSUE THREAD

**Issue by jukzi** [eclipse-equinox/equinox#499] opened 2024-02-05 08:04 UTC
i got this two log entries after another:

eclipse.buildId=4.31.0.I20240131-1800
java.version=21.0.2

```
org.eclipse.equinox.p2.touchpoint.natives
Warning
Mon Feb 05 08:55:58 CET 2024
Could not remove temporary backup directory (it is safe to manually delete it and its contents): C:\Users\jkubitz\AppData\Local\Temp\C__Users_jkubitz_platform-2024-01-10_eclipse_1be71e04-0019-45a0-9663-13b0971d78eb

```

```
Exception saving profile preferences

org.osgi.service.prefs.BackingStoreException: Exception saving preferences to: C:/Users/jkubitz/platform-2024-01-10/eclipse/p2/org.eclipse.equinox.p2.engine/profileRegistry/C__Users_jkubitz_platform-2024-01-10_eclipse.profile/.data/.settings/org.eclipse.equinox.p2.artifact.repository.prefs.
	at org.eclipse.core.internal.preferences.EclipsePreferences.write(EclipsePreferences.java:304)
	at org.eclipse.core.internal.preferences.EclipsePreferences.save(EclipsePreferences.java:998)
	at org.eclipse.equinox.internal.p2.engine.ProfilePreferences.doSave(ProfilePreferences.java:141)
	at org.eclipse.equinox.internal.p2.engine.ProfilePreferences$SaveJob.run(ProfilePreferences.java:54)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.nio.file.NoSuchFileException: C:\Users\jkubitz\platform-2024-01-10\eclipse\p2\org.eclipse.equinox.p2.engine\profileRegistry\C__Users_jkubitz_platform-2024-01-10_eclipse.profile\.data\.settings\org.eclipse.equinox.p2.artifact.repository.prefs
	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
	at java.base/sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:403)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:291)
	at java.base/java.nio.file.Files.move(Files.java:1430)
	at org.eclipse.core.internal.preferences.EclipsePreferences.write(EclipsePreferences.java:296)
	... 4 more
```

i don't understand the 2nd stacktrace as there is a File.exists() check in front.

**Comment by jukzi** [comment] 2024-02-05 08:07
code was last edited by @HannesWell @iloveeclipse 
83317a891ebd82af4f5a30053d3851cc3cbfc2b3 "Move preference files as atomic-operation"

**Comment by jukzi** [comment] 2024-02-05 08:08
the change was supposed to fix https://github.com/eclipse-equinox/equinox/issues/7 but this error message looks that - seems unfixed.

**Comment by merks** [comment] 2024-02-05 08:41
It probably should be testing isRegularFile not just exists, but I doubt there is a folder here causing this problem...

**Comment by laeubi** [comment] 2024-02-05 09:03
The problem is that on windows an atomic move / rename can cause issues because windows has probably not flushed this and then there are issues.

There are some JDK issues around: https://bugs.openjdk.org/browse/JDK-8081293

so one can retry the move, or fall back to copy and delete, there are even some cases where on windows a replace does not work but using new FileOutputStrem() works and so on, so care must be taken here if one only relies on "atomic" operations ...

**Comment by iloveeclipse** [comment] 2024-02-05 09:12
> The problem is that on windows

I see the issue on Linux too

**Comment by laeubi** [comment] 2024-02-05 09:22
> > The problem is that on windows
> 
> I see the issue on Linux too

Then wee need a stacktrace there as well.

**Comment by iloveeclipse** [comment] 2024-02-05 09:23
> Then wee need a stacktrace there as well.

See #7

**Comment by laeubi** [comment] 2024-02-05 09:27
All the referenced exceptions point to some lines that seem not match so the code has changed in the meanwhile, we need stack traces that match the current platform master.

**Comment by merks** [comment] 2024-02-05 09:31
Just modifying the available update sites will invoke this same code, which of course works fine for me.  Though it seems to save twice.

As a result, one thing to noticed is that the lock is not all that useful because the first save:

![image](https://github.com/eclipse-equinox/equinox/assets/208716/0ac1f2d4-a375-4901-a1d7-829731e81c22)

uses a different preferences instance than the second save:

![image](https://github.com/eclipse-equinox/equinox/assets/208716/42ca4eac-f660-45cf-b61b-6ef82af88498)

I'm using Java 17 not 21 though...

**Comment by laeubi** [comment] 2024-02-05 09:33
> As a result, one thing to noticed is that the lock is not all that useful because the first save:

I think the lock has to be static anyways as there is only one file system and not one per instance.

**Comment by merks** [comment] 2024-02-05 10:07
@laeubi 

All the stack traces line up for me:

![image](https://github.com/eclipse-equinox/equinox/assets/208716/980c5da3-8699-4036-8dea-dce931843185)

Also I grabbed Java 21.0.2 so I also see the same lines (for Windows) as @jukzi  for that....

**Comment by laeubi** [comment] 2024-02-05 10:12
> All the stack traces line up for me:

For **Windows** yes, as these seem to be recent, but not the ones from the "old" issue referenced by @iloveeclipse for **Linux**...

**Comment by iloveeclipse** [comment] 2024-02-05 10:17
Just got this one running p2 director app on console. SDK build is 4.31.0.I20240201-1222
```
!ENTRY org.eclipse.equinox.preferences 4 0 2024-02-05 11:14:32.268
!MESSAGE Exception saving preferences to: /workspaces/socbm599/aloskuto/ws-e4x/opt/93000/src/segments/eclipse/packages/generated/director/p2/org.eclipse.equinox.p2.engine/profileRegistry/SDKProfile.profile/.data/.settings/org.eclipse.equinox.p2.artifact.repository.prefs.
!STACK 0
java.nio.file.NoSuchFileException: /workspaces/socbm599/aloskuto/ws-e4x/opt/93000/src/segments/eclipse/packages/generated/director/p2/org.eclipse.equinox.p2.engine/profileRegistry/SDKProfile.profile/.data/.settings/org.eclipse.equinox.p2.artifact.repository.prefs.bak -> /workspaces/socbm599/aloskuto/ws-e4x/opt/93000/src/segments/eclipse/packages/generated/director/p2/org.eclipse.equinox.p2.engine/profileRegistry/SDKProfile.profile/.data/.settings/org.eclipse.equinox.p2.artifact.repository.prefs
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
        at java.base/sun.nio.fs.UnixFileSystem.move(UnixFileSystem.java:934)
        at java.base/sun.nio.fs.UnixFileSystemProvider.move(UnixFileSystemProvider.java:309)
        at java.base/java.nio.file.Files.move(Files.java:1430)
        at org.eclipse.core.internal.preferences.EclipsePreferences.write(EclipsePreferences.java:296)
        at org.eclipse.core.internal.preferences.EclipsePreferences.save(EclipsePreferences.java:998)
        at org.eclipse.equinox.internal.p2.engine.ProfilePreferences.doSave(ProfilePreferences.java:141)
        at org.eclipse.equinox.internal.p2.engine.ProfilePreferences$SaveJob.run(ProfilePreferences.java:54)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by laeubi** [comment] 2024-02-05 10:22
Thanks I think it is simply that the lock has to be static, it will happen that two threads enter the section and see the file is then, then both try to move the file while one has already gone.

**Comment by HannesWell** [comment] 2024-02-05 19:28
> > As a result, one thing to noticed is that the lock is not all that useful because the first save:
> 
> I think the lock has to be static anyways as there is only one file system and not one per instance.

But usually there should only be one file per logical preference node and those files could be written concurrently.

We would/could ensure that there is only one EclipsePreference object per logical node, then the instance lock would be sufficient.
But for that we would have to fix places like the following and check the code-base if there are more.

https://github.com/eclipse-equinox/equinox/blob/bb14aff409a35ec205150c5f517da725d6d64578/bundles/org.eclipse.equinox.preferences/src/org/eclipse/core/internal/preferences/EclipsePreferences.java#L475-L493

**Comment by jukzi** [comment] 2024-02-06 07:34
https://bugs.java.com/bugdatabase/view_bug?bug_id=JDK-8325302

**Comment by HannesWell** [comment] 2024-02-12 23:20
Fixed with https://github.com/eclipse-equinox/equinox/pull/500#issuecomment-1927125527

**Closed by HannesWell** 2024-02-12 23:20 UTC
